---
title: "Works in Progress"
listing:
  type: default
  contents:
    - "*.qmd"
---

**Exploring the Effect of Exchange Rate Volatility on Macroeconomic Outcomes, and the Role of the IPS**

There is an extensive literature on the effects of exchange rate shocks on various macroeconomic indicators. The International Price System (IPS) as described by Gopinath (2015) helps in explaining the differential impacts of exchange rate shocks on inflation across different countries. Since a significant share of global trades are invoiced in USD, the dollar enjoys a ‘privileged insularity’, as regards inflation, compared to the rest of the world (ROW). In other words, exchange rate shocks on dollar with respect to, say, an emerging market’s (EM) currency tend to cause changes in inflation in the EM but not in the U.S.. I would like to build upon this finding to investigate the relationship between exchange rate volatility shocks on some economic indicators and the role that IPS may play in explaining differential outcomes across countries.

**Is U.S. current account deficit justified?**

From a global perspective, justification for current account surpluses/deficits are dependent on the profitability of a country’s investment opportunities relative to the rest of the world. Capital flow in exchange for debt asset is a significant portion of total asset flow, and it is presumed that this type of capital generates enough additional capital to be able to repay the debt plus the borrowing cost. However, debtors could default if the underlying purpose for borrowing was not as productive as initially assessed. This implies that – at least conceptually – there are optimal levels of capital flows given a set of opportunities available within a country relative to others. Data suggests that the U.S. is a net receiver of debt capital, which contributes towards financing its current account deficit. This fact begs the question: Is the U.S.’s position as a net debtor justified in terms of its opportunities relative to the rest of the world?

**Estimating the Effects of Exchange Rate Objectives on the Fed**

Romer and Romer (2004) develop a measure of U.S. monetary policy shocks that is relatively free of endogenous and anticipatory movements. They noted, however, that the estimated shocks still contain other factors not related to public forecasts on present output and inflation, and their future paths. Some of these factors include political pressure, operating procedure of the Fed, tastes and goals of the Fed, Fed’s pursuit of other objectives, etc. Drechsel (2024) isolates the effect of political pressure by estimating the political pressure shock, then he argues that this shock is publicly observed, and thus has a propagation mechanism that is different from traditional monetary policy shock (as estimated by Romer and Romer (2004)). In the same light, I hope to:

1. isolate the effect of the exchange rate objective of the Fed by estimating the “exchange rate objective shock”, and

2. argue that this exchange rate objective shock is publicly observable, and thus has a propagation mechanism that is different from traditional Romer and Romer (2004) monetary policy shock.


**Do RTAs Kill the Trade-Creation Effects of Migration? An analysis of the European Economic Area (EEA) Agreement**

International trade and migration are two important components of globalization, and they have followed similar trends over the past century. Although governments around the world have had a favorable view of trade, the same cannot be said of migration. There have been numerous studies exploring the linkages between trade and migration, and most findings have shown that the causal effect of migration on trade is well-founded. There could, however, be distortions in these trade-creation effects, one of which occurs when trade agreements are struck. This paper examines this distortion in the case of the European Economic Area (EEA) agreement which came into force in 1994. Using data on bilateral export, immigration and emigration for ten of the pioneering countries between 1980 and 2006, I find that although immigration does have an export-creation effect, the EEA agreement makes immigration export-hindering. This agreement does not, however, seem to have any impact on the export-creation effect of emigration.